Vagrant.configure("2") do |config|

   config.vm.define "apache2" do |wordpresshost|  # Definicion Wordpress
      wordpresshost.vm.box = "ubuntu/focal64"
      wordpresshost.vm.network "private_network", ip: "192.168.56.10", nic_type: "virtio"
      wordpresshost.vm.hostname = "apache"
      wordpresshost.vm.provider :virtualbox do |vb|
          vb.name = "apache2"
          vb.memory = "1024"
          vb.cpus = 2
          # La primera interfaz de red (10.0.2.15) la modificamos a virtio
          vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      end
      wordpresshost.vm.provision :shell, path:"install_wordpress.sh"
  end

  config.vm.define "mysql" do |mysqlhost|   # Definicion VM MySQL
      mysqlhost.vm.box = "ubuntu/focal64"
      mysqlhost.vm.network "private_network", ip: "192.168.56.11", nic_type: "virtio"
      mysqlhost.vm.hostname = "mysql"
      mysqlhost.vm.provider :virtualbox do |vb|
          vb.name = "mysqlhost"
          vb.memory = "1024"
          vb.cpus = 2
          # La primera interfaz de red (10.0.2.15) la modificamos a virtio
          vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      end
      mysqlhost.vm.provision :shell, path:"install_mysql.sh"
  end
end
