# file_to_disk_1 = Dir.home + '/VirtualBox VMs/Disks/glstr1.vdi'
# file_to_disk_2 = Dir.home + '/VirtualBox VMs/Disks/glstr2.vdi'
# file_to_disk_3 = Dir.home + '/VirtualBox VMs/Disks/glstr3.vdi'

# FILE_BASE_NAME=Dir.home + '/VirtualBox VMs/Disks/glst'

FILE_BASE_NAME="/media/sd256/jicg/drives/swarm/glstr"
DISK_SIZE = 20 * 1024
NODES=3
BOX="ubuntu/focal64"
BASE_IP="192.168.56."

Vagrant.configure("2") do |config|  #{
  config.vm.box = BOX
  config.vm.provision "shell", :path => "install_software.sh"

  (1..NODES).each do |i| #{
          hostname="node#{i}"
          config.vm.define hostname do |node| #{
              filename = "#{FILE_BASE_NAME}#{i}.vdi"
              ip="#{BASE_IP}#{i+10}"
              node.vm.box = "ubuntu/focal64"
              node.vm.network "private_network", ip: ip, nic_type: "virtio"
              node.vm.hostname = hostname
              node.vm.provision :shell, path:"configure_node.sh",
                 env: {
                    "NODES" => NODES,
                    "N" => i,
                    "BASE_IP" => BASE_IP
                 }
              node.disksize.size = '20GB'
              node.vm.provider :virtualbox do |vb| #{
                  vb.name = hostname
                  vb.memory = "2048"
                  vb.cpus = 2
                  vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
                  unless File.exist?(filename) #{
                      vb.customize ['createhd', '--filename', filename, '--size', DISK_SIZE ]
                  end #}
                  vb.customize ['storageattach', :id, '--storagectl', 'SCSI', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', filename]
              end #}
          end #}
  end #}

end #}
