file_to_disk_1 = Dir.home + '/VirtualBox VMs/Disks/glstr1.vdi'
file_to_disk_2 = Dir.home + '/VirtualBox VMs/Disks/glstr2.vdi'
file_to_disk_3 = Dir.home + '/VirtualBox VMs/Disks/glstr3.vdi'
disk_size = 20 * 1024

Vagrant.configure("2") do |config|

  config.vm.define "manager" do |manager|
      manager.vm.box = "ubuntu/jammy64"
      manager.vm.network "private_network", ip: "192.168.56.10", nic_type: "virtio"
      manager.vm.hostname = "manager"
      manager.vm.provision :shell, path:"bootstrap.sh"
      manager.disksize.size = '20GB'
      manager.vm.provider :virtualbox do |vb|
          vb.name = "manager"
          vb.memory = "2048"
          vb.cpus = 2
          vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
          unless File.exist?(file_to_disk_3)
              vb.customize ['createhd', '--filename', file_to_disk_3, '--size', disk_size ]
          end
          vb.customize ['storageattach', :id, '--storagectl', 'SCSI', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', file_to_disk_3]
      end
  end

  config.vm.define "docker1" do |docker1|
      docker1.vm.box = "ubuntu/jammy64"
      docker1.vm.network "private_network", ip: "192.168.56.11", nic_type: "virtio"
      docker1.vm.hostname = "docker1"
      docker1.vm.provision :shell, path:"bootstrap.sh"
      docker1.disksize.size = '20GB'
      docker1.vm.provider :virtualbox do |vb|
          vb.name = "docker1"
          vb.memory = "3064"
          vb.cpus = 2
          vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
          unless File.exist?(file_to_disk_1)
              vb.customize ['createhd', '--filename', file_to_disk_1, '--size', disk_size ]
          end
          vb.customize ['storageattach', :id, '--storagectl', 'SCSI', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', file_to_disk_1]
      end
  end

  config.vm.define "docker2" do |docker2|
      docker2.vm.box = "ubuntu/jammy64"
      docker2.vm.network "private_network", ip: "192.168.56.12", nic_type: "virtio"
      docker2.vm.hostname = "docker2"
      docker2.vm.provision :shell, path:"bootstrap.sh"
      docker2.disksize.size = '20GB'
      docker2.vm.provider :virtualbox do |vb|
          vb.name = "docker2"
          vb.memory = "3064"
          vb.cpus = 2
          vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
          unless File.exist?(file_to_disk_1)
            vb.customize ['createhd', '--filename', file_to_disk_2, '--size', disk_size ]
          end
          vb.customize ['storageattach', :id, '--storagectl', 'SCSI', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', file_to_disk_2]
      end
  end
end
