Vagrant.configure("2") do |config|
   config.vm.box = "ubuntu/bionic64"
    
   # Configuramos el nombre del Host
   config.vm.hostname = "docker"
 
   # Le decimos cual es el script de configuracion que queremos ejecutar
   config.vm.provision :shell, path:"bootstrap.sh"

   # Aumentamos el tamaño de nuestro disco duro
   config.disksize.size = '20GB'

   # Ponemos una red privada:
   config.vm.network "private_network", ip: "192.168.40.10", nic_type: "virtio"

   # Configuramos el Hardware de nuestra VM.
   config.vm.provider "virtualbox" do |vb|
    vb.name = "docker"
    vb.memory = "3048"   # 3 GB de RAM
    vb.cpus = 3          # 3 Cores
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
  end

end
