Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    
    # Configuramos el nombre del Host
    config.vm.hostname = "jupyter"
 
    # Le decimos cual es el script de configuracion que queremos ejecutar
    config.vm.provision :shell, path:"bootstrap.sh"

   config.vm.network "private_network", ip: "192.168.50.15", nic_type: "virtio"

   # Configuramos el Hardware de nuestra VM.
   config.vm.provider "virtualbox" do |vb|
    vb.name = "jupyter"
    vb.memory = "2048"   # 2048 Mb de RAM
    vb.cpus = 2          # 3 Cores
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
  end

end
