Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    # Configuramos el nombre del Host
    config.vm.hostname = "hadoop01"


    # Le decimos cual es el script de configuracion que queremos ejecutar
    config.vm.provision :shell, path:"bootstrap.sh",
           env: {
            "NODE_IP" => "192.168.50.20"
            }


   config.vm.network "private_network", ip: "192.168.50.20", nic_type: "virtio"

   # Configuramos el Hardware de nuestra VM.
   config.vm.provider "virtualbox" do |vb|
    vb.name = "jupyter"
    vb.memory = "2048"   # 2048 Mb de RAM
    vb.cpus = 2          # 3 Cores
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end

end

