Vagrant.configure("2") do |config|

  config.vm.define "host1" do |host1|  # Definicion para una primera VM.
      host1.vm.box = "ubuntu/focal64"
      host1.vm.network "public_network", nic_type: "virtio", bridge: "enp0s20f0u1u4"
      host1.vm.hostname = "host1"
      host1.vm.provider :virtualbox do |vb|
          vb.name = "host1"
          vb.memory = "1024"
          # La primera interfaz de red (10.0.2.15) la modificamos a virtio
          vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      end
  end
end
