Vagrant.configure("2") do |config|

  config.vm.define "host1" do |host1|  # Definicion para una primera VM.
      host1.vm.box = "ubuntu/focal64"
      host1.vm.network "private_network", ip: "192.168.50.10", nic_type: "virtio"
      host1.vm.hostname = "host1"
      host1.vm.provider :virtualbox do |vb|
          vb.name = "host1"
          vb.memory = "1024"
          # La primera interfaz de red (10.0.2.15) la modificamos a virtio
          vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      end
  end

  config.vm.define "host2" do |host2|   # Definicion para una segunda VM.
      host1.vm.box = "ubuntu/focal64"
      host2.vm.network "private_network", ip: "192.168.50.11", nic_type: "virtio"
      host2.vm.hostname = "host2"
      host2.vm.provider :virtualbox do |vb|
          vb.name = "host2"
          vb.memory = "1024"
          # La primera interfaz de red (10.0.2.15) la modificamos a virtio
          vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      end
  end
end
